-include ../common/common.am
.DEFAULT_GOAL := all
all: pdf html


SOURCES = Intro.md \
		  build.md \
		  command_list.md \
		  bench.md \
          crl.md \
          dgst.md \
          ecparam.md \
          enc.md \
		  genkey.md \
		  hash.md \
		  md5.md \
		  pkcs12.md \
		  pkey.md \
		  rand.md \
		  req.md \
		  rsa.md \
		  s_client.md \
		  verify.md \
		  x509.md

PDF = wolfCLU_Manual.pdf

.PHONY: html-prep
html-prep:

.PHONY: pdf-prep
pdf-prep:
