-include ../common/common.am
.DEFAULT_GOAL := all
all: pdf html


SOURCES = chapter01.md \
		  chapter02.md \
		  chapter03.md \

PDF = wolfsentry.pdf

.PHONY: html-prep
html-prep:

.PHONY: pdf-prep
pdf-prep:
