-include ../common/common.am
.DEFAULT_GOAL := all
all: pdf html


SOURCES = section01.md \
		  section02.md \
		  section03.md \
		  section04.md

PDF  = wolfSSL-Tuning-Guide.pdf
DOXYFILE = Doxyfile


.PHONY: html-prep
html-prep:

.PHONY: pdf-prep
pdf-prep:
